version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run:
          name: Run linter
          command: echo branch
#      - node/install-packages:
#          pkg-manager: npm
#      - run:
#          name: Run linter
#          command: npm run lint:all
#      - run:
#          name: Run tests
#          command: npm run test:all
#      - store_test_results:
#          path: reports/test

  test-and-publish:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - run:
          name: Run linter
          command: echo tags
#      - node/install-packages:
#          pkg-manager: npm
#      - run:
#          name: Run linter
#          command: npm run lint:all
#      - run:
#          name: Run tests
#          command: npm run test:all
#      - store_test_results:
#          path: reports/test
workflows:
  development:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
  publish:
    jobs:
      - test-and-publish:
          filters:
            tags:
              only: /.*/


