version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  test_and_build_job:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
          with-cache: false
      - run:
          name: Run linter
          command: npm run lint:all
      - run:
          name: Run tests
          command: npm run test:all
      - run:
          name: Run build
          command: npm run build:all
      - store_test_results:
          path: reports/test
      - persist_to_workspace:
          root: dist
          paths:
            - .

  publish_job:
    docker:
      - image: cimg/node:16.17.0
    steps:
      - checkout
      - attach_workspace:
          at: dist
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN" > .npmrc
      - run:
          name: Publish core library
          command: npm publish dist/libs/core --access public
      - run:
          name: Publish material library
          command: npm publish dist/libs/material --access public

workflows:
  development:
    jobs:
      - test_and_build_job:
          filters:
            tags:
              only: /.*/
      - publish_job:
          requires:
            - test_and_build_job
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/


